# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b87df043533951076de39778529b78316d7b0a3db697e6a3642de87061061d78f4265c4a4f1f9113bf3b98e9ba00d3b5664cdcdab76f14cfd250c7e98fc4821b

test:
  secret_key_base: 36a50c1f2a3e4d1b924a2c0241e3a7cb70ed3934a7da578d484189d1a37e7610c0fd20a6da8cc18ea414f54b69231938e48687056313d1969162ee25fb5d1df5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
